# Generated by Django 4.2 on 2023-05-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'app_categories',
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=200)),
                ('menu_desc', models.CharField(max_length=200)),
                ('menu_img', models.FileField(upload_to='menus/images/')),
                ('menu_ingredient', models.CharField(max_length=200)),
                ('menu_price', models.FloatField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restro.category')),
            ],
            options={
                'db_table': 'app_menus',
            },
        ),
    ]
