# Generated by Django 4.2 on 2023-05-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_restro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuModel',
            new_name='Menu',
        ),
    ]
