# Generated by Django 4.2 on 2023-05-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restro', '0002_rename_menumodel_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_img',
            field=models.FileField(blank=True, upload_to='menus/images/'),
        ),
    ]
